---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---
require "base.ui.window.GUIBlindBoxItem"

local UIBlindBoxLayout = class("UIBlindBoxLayout", IGUILayout) ---@class UIBlindBoxLayout : IGUILayout

function UIBlindBoxLayout:onLoad()
    local llRoot = self:getChildWindow("BlindBoxLayout", GUIType.Layout)
    local llContent = self:getChildWindow("BlindBoxLayout-Content", GUIType.Layout)
    local height = math.min(llRoot:GetPixelSize().y, math.max(llContent:GetPixelSize().y, 692))
    local width = math.min((height / 692) * 1199, llRoot:GetPixelSize().x)
    llContent:SetWidth({ 0, width })
    llContent:SetHeight({ 0, height })

    local btnBackClose = self:getChildWindow("BlindBoxLayout-Back-Close", GUIType.Button)
    btnBackClose:registerEvent(GUIEvent.ButtonClick, function()
        GUIBlindBoxLayout:hide(true)
    end)
    local tvTitle = self:getChildWindow("BlindBoxLayout-Title", GUIType.StaticText)
    tvTitle:SetText(Lang:getString("blind.box.title"))
    local ivClose = self:getChildWindow("BlindBoxLayout-Close", GUIType.StaticImage)
    ivClose:registerEvent(GUIEvent.Click, function()
        GUIBlindBoxLayout:hide(true)
    end)
    self.btnHelp = self:getChildWindow("BlindBoxLayout-Help", GUIType.Button)
    self.btnHelp:registerEvent(GUIEvent.ButtonClick, function()
        GUICommonActivityTextDialog:showText("blind.box.help.title", "blind.box.help.content")
    end)
    self.tvTime = self:getChildWindow("BlindBoxLayout-Time", GUIType.StaticText)
    self.tvHint = self:getChildWindow("BlindBoxLayout-Hint", GUIType.StaticText)
    self.tvHint:SetText(Lang:getString("blind.box.bottom.hint"))

    self.llBoxs = self:getChildWindow("BlindBoxLayout-Boxs", GUIType.Layout)
    self.items = {}

    self:registerDataCallBack("BlindBoxOpenResult", function(data)
        self:onBlindBoxOpenResult(data)
    end, JsonBuilderProcessor)

    LuaTimer:scheduleTimer(function()
        self:onSecondTick()
    end, 1000, 1000)
end

function UIBlindBoxLayout:isShowAnim()
    return false
end

function UIBlindBoxLayout:initBoxList(blindBoxList)
    GUIBlindBoxMain:show()
    self:clearBoxList()
    local width = self.llBoxs:GetPixelSize().x / 3
    for pos, blindBox in pairs(blindBoxList) do
        local config = BlindBoxConfig:getBlindBoxById(blindBox.boxId)
        if config then
            config.openTimes = blindBox.openTimes
            config.dayOpenTimes = blindBox.dayOpenTimes
            local item = GUIBlindBoxItem.new()
            item:setArea({ 0, (pos - 1) * width }, { 0, 0 }, { 0, width }, { 1, 0 })
            item:onDataChanged(config)
            self.items[config.id] = item
            self.llBoxs:AddChildWindow(item.root)
        end
    end
end

function UIBlindBoxLayout:onBlindBoxEnd()
    if self:isShow() then
        CommonActivityRewardPreview.builder()
                                   .setTitleText("common.activity.tip.title")
                                   .setCenterTip(Lang:getString("common.activity.end.tip"))
                                   .show()
    end
    self:clearBoxList()
    GUIManager:removeShowQueue(GUIBlindBoxLayout)
    GUIBlindBoxMain:hide()
    GUIBlindBoxLayout:hide(true)
    GUIBlindBoxRewardList:hide()
    GUICommonActivityTextDialog:hide()
end

function UIBlindBoxLayout:resetBoxTimes()
    ---@param item GUIBlindBoxItem
    for _, item in pairs(self.items) do
        item.data.openTimes = 0
    end
end

function UIBlindBoxLayout:onSecondTick()
    if not self:isShow() then
        return
    end
    if CommonActivity:getBlindBoxInfo().lastTime >= DateUtil.getDaySeconds() then
        local text = string.format(Lang:getString("common.activity.day"),
                tostring(math.floor(CommonActivity:getBlindBoxInfo().lastTime / DateUtil.getDaySeconds())))
        self.tvTime:SetText(text)
    else
        self.tvTime:SetText(DateUtil.getFormatTime(CommonActivity:getBlindBoxInfo().lastTime))
    end
    ---@param item GUIBlindBoxItem
    for _, item in pairs(self.items) do
        item:updateTimeOrTimes()
    end
end

function UIBlindBoxLayout:clearBoxList()
    self.items = {}
    self.llBoxs:CleanupChildren()
end

function UIBlindBoxLayout:hide(force)
    if not force then
        return
    end
    self.super.hide(self)
end

function UIBlindBoxLayout:onBlindBoxOpenResult(data)
    ---计算魔方价值
    local worth = 0
    for _, item in pairs(data.results) do
        local reward = CommonActivityRewardConfig:getRewardById(item.rewardId)
        if reward then
            worth = worth + reward.price
        end
    end
    local config = BlindBoxConfig:getBlindBoxById(data.boxId)
    if not config then
        return
    end
    local percent = BlindBoxRewardConfig:getRewardPercentByWorth(config.worthGroupId, worth) .. "%"
    local text = string.format(Lang:getString("blind.box.reward.tip"), worth, percent)
    CommonActivityShowReward.builder()
                            .setBottomTip(text)
                            .setRewardView(data.results)
                            .setHideLeftButton()
                            .setRightButton("common.activity.sure")
                            .show()
    config.openTimes = data.openTimes
    config.dayOpenTimes = data.dayOpenTimes
    local item = self.items[data.boxId] ---@type GUIBlindBoxItem
    if item then
        item:updateTimeOrTimes()
    end
end

return UIBlindBoxLayout