---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 21:10
---
GUICommonActivityTab = class("GUICommonActivityTab", IGUIWindow) ---@class GUICommonActivityTab

function GUICommonActivityTab:onLoad()
    self.ivSelected = self:getChildWindowByName("CommonActivityTab-Selected", GUIType.StaticImage)
    self.ivSelected:SetVisible(false)
    self.ivRedPoint = self:getChildWindowByName("CommonActivityTab-Red-Point", GUIType.StaticImage)
    self.ivRedPoint:SetVisible(false)
    self.ivText = self:getChildWindowByName("CommonActivityTab-Text", GUIType.StaticText)
    self.btnClick = self:getChildWindowByName("CommonActivityTab-Click", GUIType.Button)
    self.btnClick:registerEvent(GUIEvent.ButtonClick, function()
        CommonActivityReportUtil.reportClickTab(self.activityType, self.activityId)
        GUICommonActivityLayout:showActivity(self.activityId)
    end)
end

function GUICommonActivityTab:onDataChanged(activity)
    self.activityType = activity.type
    self.activityId = activity.id
    self.ivText:SetText(Lang:getString(activity.tabLang))
end

function GUICommonActivityTab:setSelected(selected)
    self.ivSelected:SetVisible(selected)
    if selected then
        self:setRedPoint(false)
    end
    self.btnClick:SetTouchable(not selected)
end

function GUICommonActivityTab:isSelected()
    return self.ivSelected:IsVisible()
end

function GUICommonActivityTab:setRedPoint(isShowRed)
    self.ivRedPoint:SetVisible(isShowRed)
    GUICommonActivityMain:checkTabsRedPoint()
end

function GUICommonActivityTab:isHaveRedPoint()
    return self.ivRedPoint:IsVisible()
end

return GUICommonActivityTab