---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/18 10:21
---
GUIBlindBoxRewardGroup = class("GUIBlindBoxRewardGroup", IGUIWindow) ---@class GUIBlindBoxRewardGroup : IGUIWindow

function GUIBlindBoxRewardGroup:ctor(...)
    self.super.ctor(self, "BlindBoxRewardGroup.json", ...)
end

function GUIBlindBoxRewardGroup:onLoad()
    self.tvHint = self:getChildWindowByName("BlindBoxRewardGroup-Hint", GUIType.StaticText)
    self.llRewards = self:getChildWindowByName("BlindBoxRewardGroup-Rewards", GUIType.Layout)
    self.items = {}
end

function GUIBlindBoxRewardGroup:onDataChanged(data, delay)
    delay = delay or 0
    self.tvHint:SetText(Lang:getString(data.hint))
    local curXPos = 0
    self:addTimer(LuaTimer:schedule(function()
        for pos, reward in pairs(data.rewardGroup) do
            local xPos = curXPos
            self:addTimer(LuaTimer:schedule(function()
                local rewardItem = GUICommonActivityRewardItem.new(GUIBlindBoxRewardList)
                rewardItem:setRewardData(reward.reward, true)
                rewardItem:setArea({ 0, xPos }, { 0, 0 }, { 0, 68 }, { 0, 68 })
                rewardItem:SetEffectMask("set:common_christmas_icon.json image:img_9_mask_chrismas")
                table.insert(self.items, rewardItem)
                self.llRewards:AddChildWindow(rewardItem.root)
            end, (pos - 1) * 50))
            curXPos = curXPos + 80
        end
    end, delay))
end

function GUIBlindBoxRewardGroup:onDestroy()
    for _, item in pairs(self.items) do
        item:destroy()
    end
end