---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 21:10
---
GUICommonActivityChest = class("GUICommonActivityChests", IGUIWindow) ---@class GUICommonActivityChest : IGUIWindow

function GUICommonActivityChest:ctor(...)
    self.super.ctor(self, "CommonActivityChest.json", ...)
end

function GUICommonActivityChest:onLoad(activity)
    self.activity = activity
    self.ivLight = self:getChildWindowByName("CommonActivityChest-Light", GUIType.StaticImage)
    self.ivImage = self:getChildWindowByName("CommonActivityChest-Image", GUIType.StaticImage)
    self.llTimes = self:getChildWindowByName("CommonActivityChest-Times", GUIType.Layout)
    self.tvTimesText = self:getChildWindowByName("CommonActivityChest-Times-Text", GUIType.StaticText)
    self.root:registerEvent(GUIEvent.Click, function()
        CommonActivityReportUtil.reportRewardChestClick(self.activity.id, self.data.chestId)
        self:onClickChest()
    end)
end

function GUICommonActivityChest:onDataChanged(data)
    self.data = data
    UIHelper:setImageAdjustSize(self.ivImage, data.normalImage, 70, 70)
    self.llTimes:SetBackImage(data.timesImage)
    self.tvTimesText:SetText(string.format(Lang:getString("common.activity.times"), data.times))
    self:updateChest()
end

function GUICommonActivityChest:onClickChest()
    if self.activity.lotteryTimes >= self.data.times then
        local getChest = StringUtil.split(self.activity.getChest, ",", false, true)
        if TableUtil.tableContain(getChest, self.data.chestId) then
            local tipStr = Lang:getString("common.activity.reward.hadReceive")
            self:showRewardPreview(self.data.chestId, tipStr, "common.activity.reward.title.hadReceive")
        else
            local data = { activityId = self.activity.id, chestId = self.data.chestId }
            PacketSender:sendLuaCommonData("CommonActivityOpenChest", json.encode(data))
        end
    else
        local tipStr = string.format(Lang:getString("common.activity.reward.preview"),
                self.activity.lotteryTimes, (tonumber(self.data.times) - tonumber(self.activity.lotteryTimes)))
        self:showRewardPreview(self.data.chestId, tipStr, "common.activity.reward.preview.title")
    end
end

function GUICommonActivityChest:showRewardPreview(chestId, tipStr, title)
    local chest = CommonActivityChestConfig:getChestById(chestId)
    if not chest then
        return
    end

    CommonActivityRewardPreview.builder()
                               .setRewardViewByGroupId(chest.rewardGroupId)
                               .setTopTip(tipStr)
                               .setTitleText(title)
                               .setRewardLayoutYPos({ 0, 20 })
                               .show()
end

function GUICommonActivityChest:updateChest()
    if self.activity.lotteryTimes >= self.data.times then
        local getChest = StringUtil.split(self.activity.getChest, ",", false, true)
        if TableUtil.tableContain(getChest, self.data.chestId) then
            self.ivLight:SetVisible(false)
            UIHelper:setImageAdjustSize(self.ivImage, self.data.openImage, 70, 70)
        else
            self.ivLight:SetVisible(true)
            UIHelper:setImageAdjustSize(self.ivImage, self.data.canOpenImage, 70, 70)
        end
    else
        self.ivLight:SetVisible(false)
        UIHelper:setImageAdjustSize(self.ivImage, self.data.normalImage, 70, 70)
    end
end

return GUICommonActivityChest