---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---
require "base.ui.window.GUIBlindBoxRewardGroup"

local UIBlindBoxRewardList = class("UIBlindBoxRewardList", IGUILayout) ---@class UIBlindBoxRewardList : IGUILayout

function UIBlindBoxRewardList:onLoad()
    self.tvTitle = self:getChildWindow("BlindBoxRewardList-Title", GUIType.StaticText)
    self.ivClose = self:getChildWindow("BlindBoxRewardList-Close", GUIType.StaticImage)
    local llRewards = self:getChildWindow("BlindBoxRewardList-Rewards", GUIType.Layout)
    self.lvGroupList = IGUIListView.new("BlindBoxRewardList-Rewards-List", llRewards)
    self.lvGroupList:setItemSpace(12)
    self.ivClose:registerEvent(GUIEvent.Click, function()
        GUIBlindBoxRewardList:hide()
    end)
    local btnBackClose = self:getChildWindow("BlindBoxRewardList-Back-Close", GUIType.Button)
    btnBackClose:registerEvent(GUIEvent.ButtonClick, function()
        GUIBlindBoxRewardList:hide()
    end)
    self.wFloatReward = GUICommonActivityRewardFloat.new()
    self.root:AddChildWindow(self.wFloatReward.root)
end

function UIBlindBoxRewardList:isShowAnim()
    return false
end

function UIBlindBoxRewardList:showBlindBoxRewards(boxId)
    self.curBoxId = boxId
    self.lvGroupList:clearItems()
    local list = BlindBoxRewardConfig:getRewardListByBlindBoxId(boxId)
    local delay = 0
    local lotteryCount = 0
    for _, group in pairs(list) do
        if group.rewardGroup then
            lotteryCount = lotteryCount + group.lotteryCount
            local item = GUIBlindBoxRewardGroup.new()
            item:setWidth({ 1, 0 })
            item:onDataChanged(group, delay)
            self.lvGroupList:addItem(item)
            delay = delay + #group.rewardGroup * 50
        end
    end
    self.tvTitle:SetText(string.format(Lang:getString("blind.box.reward.list.title"), tostring(lotteryCount)))
    self:show()
end

function UIBlindBoxRewardList:onHide()
    self.lvGroupList:clearItems()
    self.wFloatReward:hide()
end

function UIBlindBoxRewardList:clickItem(item)
    self.wFloatReward:showReward(item.reward, item.root)
    CommonActivityReportUtil.reportBlindBoxView(self.curBoxId, item.reward.rewardId)
end

return UIBlindBoxRewardList
