---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---
local UICommonActivityMain = class("UICommonActivityMain", IGUILayout) ---@class UICommonActivityMain

function UICommonActivityMain:onLoad()
    self.btnEnterButton = self:getChildWindow("CommonActivityMain-Enter-Button", GUIType.Button)
    self.btnEnterButton:registerEvent(GUIEvent.ButtonClick, function()
        CommonActivityReportUtil.reportClickCommonActivity()
        GUICommonActivityLayout:show()
    end)
    self.ivEnterEffect = self:getChildWindow("CommonActivityMain-Enter-Effect", GUIType.StaticImage)
    self.ivRedPoint = self:getChildWindow("CommonActivityMain-Red-Point", GUIType.StaticImage)
    self.ivRedPoint:SetVisible(false)
end

function UICommonActivityMain:checkTabsRedPoint()
    LuaTimer:schedule(function()
        self.ivRedPoint:SetVisible(GUICommonActivityLayout:isHaveRedPoint())
    end, 1)
end

return UICommonActivityMain
