---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/16 11:09
---
local UIBlindBoxMain = class("UIBlindBoxMain", IGUILayout) ---@class UIBlindBoxMain

function UIBlindBoxMain:onLoad()
    self.btnEnterButton = self:getChildWindow("BlindBoxMain-Enter-Button", GUIType.Button)
    self.btnEnterButton:registerEvent(GUIEvent.ButtonClick, function()
        CommonActivityReportUtil.reportClickChristmas()
        GUIBlindBoxLayout:show()
    end)
    self.ivEnterEffect = self:getChildWindow("BlindBoxMain-Enter-Effect", GUIType.StaticImage)
    self.ivRedPoint = self:getChildWindow("BlindBoxMain-Red-Point", GUIType.StaticImage)
    self.ivRedPoint:SetVisible(false)
end

return UIBlindBoxMain
