---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2020/11/18 10:21
---
GUIBlindBoxItem = class("GUIBlindBoxItem", IGUIWindow) ---@class GUIBlindBoxItem : IGUIWindow

function GUIBlindBoxItem:ctor(...)
    self.super.ctor(self, "BlindBoxItem.json", ...)
end

function GUIBlindBoxItem:onLoad()
    self.btnQuestion = self:getChildWindowByName("BlindBoxItem-Question", GUIType.Button)
    self.btnShow = self:getChildWindowByName("BlindBoxItem-Show", GUIType.Button)
    self.tvName = self:getChildWindowByName("BlindBoxItem-Name", GUIType.StaticText)
    self.ivWorthIcon = self:getChildWindowByName("BlindBoxItem-Worth-Icon", GUIType.StaticImage)
    self.tvWorthText = self:getChildWindowByName("BlindBoxItem-Worth-Text", GUIType.StaticText)
    self.tvTimeOrTimes = self:getChildWindowByName("BlindBoxItem-Time-Or-Times", GUIType.StaticText)
    self.btnOpen = self:getChildWindowByName("BlindBoxItem-Open", GUIType.Button)
    self.ivPriceIcon = self:getChildWindowByName("BlindBoxItem-Price-Icon", GUIType.StaticImage)
    self.tvPriceText = self:getChildWindowByName("BlindBoxItem-Price-Text", GUIType.StaticText)
    self.btnOpen:SetText(Lang:getString("blind.box.open"))
    self.btnQuestion:registerEvent(GUIEvent.ButtonClick, function()
        GUIBlindBoxRewardList:showBlindBoxRewards(self.data.id)
    end)
    self.btnShow:registerEvent(GUIEvent.ButtonClick, function()
        GUIBlindBoxRewardList:showBlindBoxRewards(self.data.id)
    end)
    self.btnOpen:registerEvent(GUIEvent.ButtonClick, function()
        if self.data.openTimes >= self.data.totalTimes or self.data.dayOpenTimes >= self.data.dayTimes then
            return
        end
        CommonActivityReportUtil.reportBlindBoxClick(self.data.id)
        PayHelper.checkMoney(self.data.moneyType, self.data.price, function(success)
            if success then
                local data = { boxId = self.data.id }
                PacketSender:sendLuaCommonData("BlindBoxOpen", json.encode(data))
            end
        end)
    end)
end

function GUIBlindBoxItem:onDataChanged(data)
    self.data = data
    self.tvName:SetText(Lang:getString(data.name))
    self.tvWorthText:SetText(data.priceRange)
    self.ivWorthIcon:SetXPosition({ 0, -(self.tvWorthText:GetFont():GetTextExtent(data.priceRange, 1) + 5) / 2 })
    self.tvPriceText:SetText(tostring(data.price))
    self.ivPriceIcon:SetXPosition({ 0, -(self.tvPriceText:GetFont():GetTextExtent(tostring(data.price), 1) + 8) / 2 })
end

function GUIBlindBoxItem:updateTimeOrTimes()
    if self.data.openTimes >= self.data.totalTimes then
        self.ivPriceIcon:SetEnabled(false)
        self.btnOpen:SetEnabled(false)
        self.tvTimeOrTimes:SetText(Lang:getString("blind.box.open.max"))
    else
        if self.data.dayOpenTimes >= self.data.dayTimes then
            self.ivPriceIcon:SetEnabled(false)
            self.btnOpen:SetEnabled(false)
            self.tvTimeOrTimes:SetText(DateUtil.getFormatTime(CommonActivity:getBlindBoxInfo().dayLastTime))
        else
            self.ivPriceIcon:SetEnabled(true)
            self.btnOpen:SetEnabled(true)
            self.tvTimeOrTimes:SetText(string.format(Lang:getString("blind.box.open.times"),
                    tostring(self.data.dayTimes - self.data.dayOpenTimes)))
        end
    end
end